name: Build Windows App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Install dependencies
      run: npm install
    - name: Build application
      run: npm run make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: squirtle-sql-viewer-build-output
        path: out/make
